// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VwHsKnsMc_DhZQNweJ4LZsd9d2g0Ijw',
    appId: '1:405417083648:web:f3a379ba326a0c975be9e5',
    messagingSenderId: '405417083648',
    projectId: 'acctik-ce71b',
    authDomain: 'acctik-ce71b.firebaseapp.com',
    storageBucket: 'acctik-ce71b.appspot.com',
    measurementId: 'G-EPLPC2LFPD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_VwHsKnsMc_DhZQNweJ4LZsd9d2g0Ijw',
    appId: '1:405417083648:web:f3a379ba326a0c975be9e5',
    messagingSenderId: '405417083648',
    projectId: 'acctik-ce71b',
    authDomain: 'acctik-ce71b.firebaseapp.com',
    storageBucket: 'acctik-ce71b.appspot.com',
    measurementId: 'G-EPLPC2LFPD',
  );

}